name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Image Tag
        run: echo "IMAGE_TAG"=$(date +%s) >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file deployment/Dockerfile --tag shubhamdixit863/goreactfrontend2:${{env.IMAGE_TAG}}
      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Image to Docker Hub
        run: docker push shubhamdixit863/goreactfrontend2:${{env.IMAGE_TAG}}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Add step to read Kubeconfig from file
      - name: Set Kubeconfig
        run: echo "KUBECONFIG=$(cat kube.config)" >> $GITHUB_ENV

      - name: Deployment
        uses: Pablommr/kubernetes-eks@v1.2.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KUBECONFIG: ${{ env.KUBECONFIG }}
          KUBE_YAML: deployment/deployment.yaml
